--- 
abstract: The LightWeight client module for XRI Resolution
author: 
  - Toru Yamaguchi <zigorou@cpan.org>
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: XRI-Resolution-Lite
no_index: 
  directory: 
    - inc
    - t
requires: 
  Class::Accessor::Fast: 0
  HTTP::Request: 0
  LWP::UserAgent: 0
  URI: 0
  XML::LibXML: 0
  XML::LibXML::XPathContext: 0
version: 0.01
