---
abstract: 'The Lightweight client module for XRI Resolution'
author:
  - 'Toru Yamaguchi <zigorou@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: XRI-Resolution-Lite
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Carp: 0
  Class::Accessor::Fast: 0
  Filter::Util::Call: 0
  HTTP::Request: 0
  LWP::UserAgent: 0
  URI: 0
  XML::LibXML: 0
  XML::LibXML::XPathContext: 0
  parent: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.04
